# Install and load necessary packages
install.packages("gridExtra")
library(gridExtra)
library(ggplot2)

# Create the first choropleth map for nitrogen emissions
plot1 <- ggplot(data = combined_sf) +
  geom_sf(aes(fill = total_nitrogen_emissions)) +
  scale_fill_gradient(low = "lightyellow", high = "red", na.value = "white", name = "emissions") +
  labs(title = "Nitrogen Emissions Across Counties",
       subtitle = "Emissions Generated by Livestock Farms",
       fill = "Total Nitrogen Emissions") +
  theme_gray()

# Create the second choropleth map for the number of farms
plot2 <- ggplot(data = combined_sf) +
  geom_sf(aes(fill = freq)) +
  scale_fill_gradient(low = "lightyellow", high = "red", na.value = "white", name = "Farms") +
  labs(title = "Farms Per County",
       subtitle = "Number of Intensive Farms Containing Pigs",
       fill = "Freq") +
  theme_gray()

# Display the two plots side by side
grid.arrange(plot1, plot2, ncol = 2)
