library(sf)
library(sp)
library(dplyr)
library(tidyverse)
#this file contains analysis for nitrgen emissions due to number of farms per county
shp=read_sf("/home/shreshtha/Downloads/shapefiles_catalunya_comarcas/shapefiles_catalunya_comarcas.shp")

nitrogen_emissions=livestock %>%
  filter(PRODUCTION.SYSTEM == "Intensiu") %>%
  group_by(FARM.COUNTY) %>%
  summarize(total_nitrogen_emissions = sum(TOTAL.NITROGEN, na.rm = TRUE))
#combine this with the shapefile after renaming

nitrogen_emissions=nitrogen_emissions %>%
  rename(nom_comar = FARM.COUNTY)

combined_sf <- full_join(shp, nitrogen_emissions, by = "nom_comar")

ggplot(data = combined_sf) +
  geom_sf(aes(fill = total_nitrogen_emissions))  +
  scale_fill_gradient(low="lightyellow",high="red",na.value="white",name="emissions") +  # Use a color scale, e.g., viridis
  labs(title = "nitrogen emissions across counties",
       subtitle="emissions generated by livestock farms",
       fill = "total_nitrogen_emissions")+
  theme_gray()
